#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
# PocketRust Demo Cart. Dedicated to the public domain; see LICENSE.
"""Regenerate src/tables.s.

Two tables the cartridge cannot compute for itself at the speed it needs them:
a sine, for the object screen's rings and wave, and the Game Boy's frequency
register value for each note the audio screen plays.

Its output is checked in and is perfectly readable on its own; you never need to
run this to build the ROM.

    python3 tools/gentables.py > src/tables.s
"""

import math
import sys

# One turn in 256 steps. Exactly 256, so that an 8-bit angle indexes it without
# a range check and a cosine is the same table read with 64 added to the angle,
# wrapping for free. Amplitude 120 rather than 127 keeps an object centred at 80
# inside the 160-pixel screen at full swing.
SINE_LEN = 256
SINE_CENTRE = 128
SINE_AMPLITUDE = 120

# The Game Boy's pulse and wave channels are programmed with a period, not a
# frequency: the counter runs from the stored value up to 2048, so
# period = 2048 - 131072 / hertz. Rounding is done here, once, rather than in
# 8-bit arithmetic on the cartridge.
NOTES = [
    ("C3", 130.813), ("CS3", 138.591), ("D3", 146.832), ("DS3", 155.563),
    ("E3", 164.814), ("F3", 174.614), ("FS3", 184.997), ("G3", 195.998),
    ("GS3", 207.652), ("A3", 220.000), ("AS3", 233.082), ("B3", 246.942),
    ("C4", 261.626), ("CS4", 277.183), ("D4", 293.665), ("DS4", 311.127),
    ("E4", 329.628), ("F4", 349.228), ("FS4", 369.994), ("G4", 391.995),
    ("GS4", 415.305), ("A4", 440.000), ("AS4", 466.164), ("B4", 493.883),
    ("C5", 523.251), ("CS5", 554.365), ("D5", 587.330), ("DS5", 622.254),
    ("E5", 659.255), ("F5", 698.456), ("FS5", 739.989), ("G5", 783.991),
    ("GS5", 830.609), ("A5", 880.000), ("AS5", 932.328), ("B5", 987.767),
]


def rows(values, per_row=16):
    for i in range(0, len(values), per_row):
        yield values[i:i + per_row]


def main():
    # Write LF regardless of platform: the output is checked in, and a build
    # that flips line endings would make the reproducibility test report a
    # source drift that is not one.
    sys.stdout.reconfigure(newline="\n")
    print("; SPDX-License-Identifier: CC0-1.0")
    print("; PocketRust Demo Cart. Dedicated to the public domain; see LICENSE.")
    print(";")
    print("; Generated by tools/gentables.py. Nothing here is hand-written, and")
    print("; nothing here needs to be read to understand the cartridge; it is the")
    print("; arithmetic the Game Boy is too slow to do while a frame is running.")
    print()

    sine = [
        SINE_CENTRE + round(SINE_AMPLITUDE * math.sin(2 * math.pi * i / SINE_LEN))
        for i in range(SINE_LEN)
    ]
    assert all(0 <= v <= 255 for v in sine), "sine left the byte"

    print("; One full turn in 256 steps, centred on 128. Adding 64 to an 8-bit angle")
    print("; and letting it wrap is a cosine of the same angle.")
    print("sine_table:")
    for row in rows(sine):
        print("  .byte " + ", ".join(str(v) for v in row))
    print()
    print(f".assert sine_table_end - sine_table == {len(sine)}, "
          '"the sine table changed length"')
    print("sine_table_end:")
    print()

    print("; Pulse and wave period registers, low byte then high byte, one note per")
    print("; entry, ascending from C3. NOTE_C4 and friends index into this.")
    print("note_table:")
    for name, hz in NOTES:
        period = round(2048 - 131072 / hz)
        assert 0 <= period < 2048, f"{name} does not fit the 11-bit period"
        print(f"  .byte ${period & 0xff:02x}, ${period >> 8:02x}   ; {name:4s} "
              f"{hz:8.3f} Hz -> {period}")
    print()
    for i, (name, _) in enumerate(NOTES):
        print(f"NOTE_{name} = {i}")
    print()
    print(f".assert note_table_end - note_table == {2 * len(NOTES)}, "
          '"the note table changed length"')
    print("note_table_end:")


if __name__ == "__main__":
    sys.exit(main())
