; SPDX-License-Identifier: CC0-1.0
; PocketRust Demo Cart. Dedicated to the public domain; see LICENSE.
;
; Generated by tools/gentables.py. Nothing here is hand-written, and
; nothing here needs to be read to understand the cartridge; it is the
; arithmetic the Game Boy is too slow to do while a frame is running.

; One full turn in 256 steps, centred on 128. Adding 64 to an 8-bit angle
; and letting it wrap is a cosine of the same angle.
sine_table:
  .byte 128, 131, 134, 137, 140, 143, 146, 149, 151, 154, 157, 160, 163, 166, 168, 171
  .byte 174, 177, 179, 182, 185, 187, 190, 192, 195, 197, 199, 202, 204, 206, 209, 211
  .byte 213, 215, 217, 219, 221, 223, 224, 226, 228, 229, 231, 232, 234, 235, 236, 238
  .byte 239, 240, 241, 242, 243, 244, 244, 245, 246, 246, 247, 247, 247, 248, 248, 248
  .byte 248, 248, 248, 248, 247, 247, 247, 246, 246, 245, 244, 244, 243, 242, 241, 240
  .byte 239, 238, 236, 235, 234, 232, 231, 229, 228, 226, 224, 223, 221, 219, 217, 215
  .byte 213, 211, 209, 206, 204, 202, 199, 197, 195, 192, 190, 187, 185, 182, 179, 177
  .byte 174, 171, 168, 166, 163, 160, 157, 154, 151, 149, 146, 143, 140, 137, 134, 131
  .byte 128, 125, 122, 119, 116, 113, 110, 107, 105, 102, 99, 96, 93, 90, 88, 85
  .byte 82, 79, 77, 74, 71, 69, 66, 64, 61, 59, 57, 54, 52, 50, 47, 45
  .byte 43, 41, 39, 37, 35, 33, 32, 30, 28, 27, 25, 24, 22, 21, 20, 18
  .byte 17, 16, 15, 14, 13, 12, 12, 11, 10, 10, 9, 9, 9, 8, 8, 8
  .byte 8, 8, 8, 8, 9, 9, 9, 10, 10, 11, 12, 12, 13, 14, 15, 16
  .byte 17, 18, 20, 21, 22, 24, 25, 27, 28, 30, 32, 33, 35, 37, 39, 41
  .byte 43, 45, 47, 50, 52, 54, 57, 59, 61, 64, 66, 69, 71, 74, 77, 79
  .byte 82, 85, 88, 90, 93, 96, 99, 102, 105, 107, 110, 113, 116, 119, 122, 125

.assert sine_table_end - sine_table == 256, "the sine table changed length"
sine_table_end:

; Pulse and wave period registers, low byte then high byte, one note per
; entry, ascending from C3. NOTE_C4 and friends index into this.
note_table:
  .byte $16, $04   ; C3    130.813 Hz -> 1046
  .byte $4e, $04   ; CS3   138.591 Hz -> 1102
  .byte $83, $04   ; D3    146.832 Hz -> 1155
  .byte $b5, $04   ; DS3   155.563 Hz -> 1205
  .byte $e5, $04   ; E3    164.814 Hz -> 1253
  .byte $11, $05   ; F3    174.614 Hz -> 1297
  .byte $3b, $05   ; FS3   184.997 Hz -> 1339
  .byte $63, $05   ; G3    195.998 Hz -> 1379
  .byte $89, $05   ; GS3   207.652 Hz -> 1417
  .byte $ac, $05   ; A3    220.000 Hz -> 1452
  .byte $ce, $05   ; AS3   233.082 Hz -> 1486
  .byte $ed, $05   ; B3    246.942 Hz -> 1517
  .byte $0b, $06   ; C4    261.626 Hz -> 1547
  .byte $27, $06   ; CS4   277.183 Hz -> 1575
  .byte $42, $06   ; D4    293.665 Hz -> 1602
  .byte $5b, $06   ; DS4   311.127 Hz -> 1627
  .byte $72, $06   ; E4    329.628 Hz -> 1650
  .byte $89, $06   ; F4    349.228 Hz -> 1673
  .byte $9e, $06   ; FS4   369.994 Hz -> 1694
  .byte $b2, $06   ; G4    391.995 Hz -> 1714
  .byte $c4, $06   ; GS4   415.305 Hz -> 1732
  .byte $d6, $06   ; A4    440.000 Hz -> 1750
  .byte $e7, $06   ; AS4   466.164 Hz -> 1767
  .byte $f7, $06   ; B4    493.883 Hz -> 1783
  .byte $06, $07   ; C5    523.251 Hz -> 1798
  .byte $14, $07   ; CS5   554.365 Hz -> 1812
  .byte $21, $07   ; D5    587.330 Hz -> 1825
  .byte $2d, $07   ; DS5   622.254 Hz -> 1837
  .byte $39, $07   ; E5    659.255 Hz -> 1849
  .byte $44, $07   ; F5    698.456 Hz -> 1860
  .byte $4f, $07   ; FS5   739.989 Hz -> 1871
  .byte $59, $07   ; G5    783.991 Hz -> 1881
  .byte $62, $07   ; GS5   830.609 Hz -> 1890
  .byte $6b, $07   ; A5    880.000 Hz -> 1899
  .byte $73, $07   ; AS5   932.328 Hz -> 1907
  .byte $7b, $07   ; B5    987.767 Hz -> 1915

NOTE_C3 = 0
NOTE_CS3 = 1
NOTE_D3 = 2
NOTE_DS3 = 3
NOTE_E3 = 4
NOTE_F3 = 5
NOTE_FS3 = 6
NOTE_G3 = 7
NOTE_GS3 = 8
NOTE_A3 = 9
NOTE_AS3 = 10
NOTE_B3 = 11
NOTE_C4 = 12
NOTE_CS4 = 13
NOTE_D4 = 14
NOTE_DS4 = 15
NOTE_E4 = 16
NOTE_F4 = 17
NOTE_FS4 = 18
NOTE_G4 = 19
NOTE_GS4 = 20
NOTE_A4 = 21
NOTE_AS4 = 22
NOTE_B4 = 23
NOTE_C5 = 24
NOTE_CS5 = 25
NOTE_D5 = 26
NOTE_DS5 = 27
NOTE_E5 = 28
NOTE_F5 = 29
NOTE_FS5 = 30
NOTE_G5 = 31
NOTE_GS5 = 32
NOTE_A5 = 33
NOTE_AS5 = 34
NOTE_B5 = 35

.assert note_table_end - note_table == 72, "the note table changed length"
note_table_end:
